{% set version = '0.0.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: amisforinfectiousdiseases
  version: {{ version|replace("-", "_") }}

source:
  git_url: https://github.com/evandrokonzen/AMISforInfectiousDiseases-dev.git

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, rmarkdown
requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]

  host:
    # You'd think hmisc, mclust, mnornmt and weights
    # are not required at build time.  But package won't build
    # if they're not specified in the host requirements as well as
    # in the run reqs.  Maybe related to compilation with rcpp?
    - r-base >=4.1
    - r-rcpp
    - r-rcpparmadillo
    - r-hmisc
    - r-mclust
    - r-mnormt
    - r-weights

  run:
    - r-base >=4.1
    - {{native}}gcc-libs         # [win]
    - r-hmisc
    - r-mclust
    - r-mnormt
    - r-weights

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('AMISforInfectiousDiseases')"           # [not win]
    - "\"%R%\" -e \"library('AMISforInfectiousDiseases')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/evandrokonzen/AMISforInfectiousDiseases-dev
  license: MIT | GPL-3
  summary: Implement the Adaptive Importance Sampling Algorithm (AMIS) for infectious disease models
  license_family: GPL3
  license_file:
    - LICENSE.md
    - LICENSE

