package:
  name: ntd-trachoma
  version: 1.0.1dev

source:
  git_url: https://github.com/NTD-Modelling-Consortium/ntd-model-trachoma.git

build:
  noarch: python
  number: 0
  script: python -m pip install . --no-deps

requirements:
  build:
    - python
    - setuptools

  run:
    - python>=3.6
    - numpy
    - pandas
    - joblib
    - google-cloud-storage
    - matplotlib
    - openpyxl

test:
  imports:
    - trachoma
